apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: project_name
  name: project_name
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project_name
  template:
    metadata:
      labels:
        app: service-sms
    spec:
      containers:
      - image: reg.chuangjialive.com/chuangjia/test_service-sms:v27
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 20880
          timeoutSeconds: 1
        name: project_name
        ports:
        - containerPort: 20880
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 20880
          timeoutSeconds: 1
      restartPolicy: Always
